version: '2'
networks:
  default:
    external:
      name: nginx-proxy
services:
  app:
    restart: always
    links:
      - mongodb:mongodb
    environment:
      NODE_ENV: production
      LETSENCRYPT_HOST: grants.g0v.tw
      LETSENCRYPT_EMAIL: jothon-organizers@g0v.tw
      VIRTUAL_HOST: grants.g0v.tw
